name: bench

# Only run when triggered manually.
on: workflow_dispatch

jobs:
  bench:
    runs-on: ubuntu-latest
    env:
      PGPASSWORD: password
    steps:
      - uses: actions/checkout@v2
      - name: setup pgbench
        run: |
          sudo apt-get -y install python3-asyncpg python3-distro python3-numpy
          make -C _python
      - name: run
        run: |
          ./pgbench \
              --pghost=127.0.0.1 --pguser=postgres \
              --save-html=report.html --save-json=report.json \
              python-psycopg2 python-psycopg python-asyncpg
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: report.html
          path: report.html

    services:
      postgresql:
        image: "postgres:15"
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
